settings/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("warehouses/", include("warehouses.urls")),
]

warehouses/urls.py
from django.urls import path
from . import views

app_name = "warehouses"

urlpatterns = [
    path(
        "warehouse_list/",
        views.WarehouseListView.as_view(),
        name="warehouse_list",
    ),
    path(
        "storagetype_list/",
        views.StorageTypeListView.as_view(),
        name="storagetype_list",
    ),
    path(
        "cargo_list/",
        views.CargoListView.as_view(),
        name="cargo_list",
    ),
    path(
        "warehouse_detail/<int:pk>/",
        views.WarehouseDetailView.as_view(),
        name="warehouse_detail",
    ),
    path(
        "storagetype_detail/<int:pk>/",
        views.StorageTypeDetailView.as_view(),
        name="storagetype_detail",
    ),
    path(
        "cargo_detail/<int:pk>/",
        views.CargoDetailView.as_view(),
        name="cargo_detail",
    ),
]

warehouses/models.py
from django.db import models


class Warehouse(models.Model):
    name = models.CharField('Наименование склада', max_length=64, db_index=True)
    address = models.CharField('Адрес', max_length=150, null=False)
    description = models.CharField('Описание', max_length=150, null=True, blank=True)
    useful_value = models.FloatField('Площадь', null=False)

    class Meta:
        verbose_name = 'Склад'
        verbose_name_plural = 'Склады'


class StorageType(models.Model):
    name = models.CharField('Наименование типа хранения', max_length=64, db_index=True)
    description = models.CharField('Описание', max_length=150, null=True, blank=True)
    storage_value = models.FloatField('Вместимость')
    warehouse = models.ManyToManyField('Warehouse', related_name='storage_types')

    class Meta:
        verbose_name = 'Тип хранения'
        verbose_name_plural = 'Типы хранения'


class Cargo(models.Model):
    name = models.CharField('Наименование груза', max_length=64, db_index=True)
    description = models.CharField('Описание', max_length=150, null=True, blank=True)
    cargo_value = models.FloatField('Объем груза')
    cargo_weight = models.FloatField('Вес груза')
    storage_type = models.OneToOneField(StorageType, on_delete=models.CASCADE, primary_key=True)
    warehouse = models.ForeignKey(Warehouse, verbose_name='cargos', on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Груз'
        verbose_name_plural = 'Грузы'

warehouses/views.py
from .models import Warehouse, StorageType, Cargo
from django.views.generic import ListView, DetailView


class WarehouseListView(ListView):
    model = Warehouse


class WarehouseDetailView(DetailView):
    model = Warehouse


class StorageTypeListView(ListView):
    model = StorageType


class StorageTypeDetailView(DetailView):
    model = StorageType


class CargoListView(ListView):
    model = Cargo


class CargoDetailView(DetailView):
    model = Cargo

warehouses/templates/warehouses/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  <title>{% block title %}
  	Base title
  {% endblock %}</title>
</head>
<body>
  <ul>
    <li><a href="{% url 'warehouses:list_warehouse' %}"
    >Список складов</a></li>
      <li>
        <a href="{% url 'warehouses:list_storage_type' %}">Список типов хранения</a>
      </li>
      <li>
        <a href="{% url 'warehouses:list_cargo' %}">Список грузов</a>
      </li>
  </ul>
{% block body %}
	Base body
{% endblock %}
</body>
</html>

warehouses/templates/warehouses/cargo_detail.html
{% block title %}
  {{object.name}}
{% endblock %}

{% block body %}
  <h1>{{object.name}}</h1>
    {{object.category.name}}
<div>
  <a href="{% url 'warehouses:cargo_list' %}">Вернуться к списку</a>
</div>
{% endblock %}

warehouses/templates/warehouses/cargo_list.html
{% block title %}
  Виды грузов
{% endblock %}

{% block body %}
  <h1>Виды грузов:</h1>
  {% if object_list %}
    <ul>
      {% for c in object_list %}
        <li>
          <strong>{{ c.name }}</strong> .
          <strong>
            <a href="{% url 'warehouses:cargo_detail' pk=c.pk %}">
              {{ c.name }}
            </a>
               </strong>
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <h2>Пока нет грузов</h2>
  {% endif %}

{% endblock %}

warehouses/templates/warehouses/storagetype_detail.html
{% block title %}
  {{object.name}}
{% endblock %}

{% block body %}
  <h1>{{object.name}}</h1>
    {{object.category.name}}
<div>
  <a href="{% url 'warehouses:storagetype_list' %}">Вернуться к списку</a>
</div>

{% endblock %}

warehouses/templates/warehouses/storagetype_list.html
{% block title %}
  Типы хранения
{% endblock %}

{% block body %}
  <h1>Типы хранения:</h1>
  {% if object_list %}
    <ul>
      {% for type in object_list %}
        <li>
          <strong>{{ type.name }}</strong> <em>({{ type.warehouse }})</em>.
          <strong>
            <a href="{% url 'warehouses:storagetype_detail' pk=type.pk %}">
              {{ type.name }}
            </a>
               </strong>
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <h2>Пока нет типов хранения</h2>
  {% endif %}

{% endblock %}

warehouses/templates/warehouses/warehouse_detail.html
{% block title %}
  {{object.name}}
{% endblock %}

{% block body %}
  <h1>{{object.name}}</h1>
    {{object.name}}
<div>
  <a href="{% url 'warehouses:warehouse_list' %}">Вернуться к списку</a>
</div>

{% endblock %}

warehouses/templates/warehouses/warehouse_list.html
{% block title %}
  Склады
{% endblock %}

{% block body %}
  <h1>Склады:</h1>
  {% if object_list %}
    <ul>
      {% for warehouse in object_list %}
        <li>
          <strong>{{ warehouse.name }}</strong> <em>({{ warehouse.address }})</em>.
           <strong>
            <a href="{% url 'warehouses:warehouse_detail' pk=warehouse.pk %}">
                {{ warehouse.name }}
            </a>
               </strong>
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <h2>Пока нет складов</h2>
  {% endif %}

{% endblock %}